export const sourceCorpus = [
  "hello world",
  "hello-world",
  "hello_world",
  "helloWorld",
  "HelloWorld",
  "XMLParser",
  "getHTTPSUrl",
  "item3D",
  "  multiple   separators---here__now  ",
  "rock'n'roll",
  "SíDéRá",
  "",
  "   ",
] as const;

export const expectedByCase = {
  camel: [
    "helloWorld",
    "helloWorld",
    "helloWorld",
    "helloWorld",
    "helloWorld",
    "xmlParser",
    "getHttpsUrl",
    "item3D",
    "multipleSeparatorsHereNow",
    "rockNRoll",
    "síDéRá",
    "",
    "",
  ],
  capital: [
    "Hello World",
    "Hello World",
    "Hello World",
    "Hello World",
    "Hello World",
    "Xml Parser",
    "Get Https Url",
    "Item 3 D",
    "Multiple Separators Here Now",
    "Rock N Roll",
    "Sí Dé Rá",
    "",
    "",
  ],
  constant: [
    "HELLO_WORLD",
    "HELLO_WORLD",
    "HELLO_WORLD",
    "HELLO_WORLD",
    "HELLO_WORLD",
    "XML_PARSER",
    "GET_HTTPS_URL",
    "ITEM_3_D",
    "MULTIPLE_SEPARATORS_HERE_NOW",
    "ROCK_N_ROLL",
    "SÍ_DÉ_RÁ",
    "",
    "",
  ],
  header: [
    "Hello-World",
    "Hello-World",
    "Hello-World",
    "Hello-World",
    "Hello-World",
    "Xml-Parser",
    "Get-Https-Url",
    "Item-3-D",
    "Multiple-Separators-Here-Now",
    "Rock-N-Roll",
    "Sí-Dé-Rá",
    "",
    "",
  ],
  kebab: [
    "hello-world",
    "hello-world",
    "hello-world",
    "hello-world",
    "hello-world",
    "xml-parser",
    "get-https-url",
    "item-3-d",
    "multiple-separators-here-now",
    "rock-n-roll",
    "sí-dé-rá",
    "",
    "",
  ],
  lower: [
    "hello world",
    "hello world",
    "hello world",
    "hello world",
    "hello world",
    "xml parser",
    "get https url",
    "item 3 d",
    "multiple separators here now",
    "rock n roll",
    "sí dé rá",
    "",
    "",
  ],
  pascal: [
    "HelloWorld",
    "HelloWorld",
    "HelloWorld",
    "HelloWorld",
    "HelloWorld",
    "XmlParser",
    "GetHttpsUrl",
    "Item3D",
    "MultipleSeparatorsHereNow",
    "RockNRoll",
    "SíDéRá",
    "",
    "",
  ],
  sentence: [
    "Hello world",
    "Hello world",
    "Hello world",
    "Hello world",
    "Hello world",
    "Xml parser",
    "Get https url",
    "Item 3 d",
    "Multiple separators here now",
    "Rock n roll",
    "Sí dé rá",
    "",
    "",
  ],
  snake: [
    "hello_world",
    "hello_world",
    "hello_world",
    "hello_world",
    "hello_world",
    "xml_parser",
    "get_https_url",
    "item_3_d",
    "multiple_separators_here_now",
    "rock_n_roll",
    "sí_dé_rá",
    "",
    "",
  ],
  title: [
    "Hello World",
    "Hello World",
    "Hello World",
    "Hello World",
    "Hello World",
    "Xml Parser",
    "Get Https Url",
    "Item 3 D",
    "Multiple Separators Here Now",
    "Rock N Roll",
    "Sí Dé Rá",
    "",
    "",
  ],
  upper: [
    "HELLO WORLD",
    "HELLO WORLD",
    "HELLO WORLD",
    "HELLO WORLD",
    "HELLO WORLD",
    "XML PARSER",
    "GET HTTPS URL",
    "ITEM 3 D",
    "MULTIPLE SEPARATORS HERE NOW",
    "ROCK N ROLL",
    "SÍ DÉ RÁ",
    "",
    "",
  ],
} as const;
